apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-auth
    spec:
      containers:
      - name: weatherapp-auth
        image: eltelawi/weather-app:auth-1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_USER
            value: authuser
          - name: DB_PASSWORD
#            value: "my-secret-pw"
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: auth-password
          - name: DB_NAME
            value: weatherapp
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
#            value: "xco0sr0fh4e52x03g9mv"          
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: secret-key